### ISSUE TITLE
Enable Zone Redundancy as an Option on Multi-Tenant Scenerio

### ISSUE THREAD

**Issue by kunalbabre** [Azure/appservice-landing-zone-accelerator#114]
Implement Zone Redundancy as an optional feature that can be enabled at time of deployment. This requires premium SKU instead of the standard that current scenario uses.

- [x] Terraform implementation 
- [x] Bicep implementation

**Comment by thotheod** [comment]
**Bicep**: I have limited the available options with a config map of App Service Plan SKUs to the pre-defined values shown after. The ones ending with _AZ, are deploying at least three instances in three Availability Zones. The desired value can be set on the parameter file of the deployment
```
// Defines the name, tier, size, family and capacity of the App Service Plan. Plans ending to _AZ, are deploying at least three instances in three Availability Zones. EP* is only for functions'
        // select one from: 'B1', 'B2', 'B3', 'S1', 'S2', 'S3', 'P1V3', 'P2V3', 'P3V3', 'P1V3_AZ', 'P2V3_AZ', 'P3V3_AZ', 'EP1', 'EP2', 'EP3' 
        "webAppPlanSku": {
            "value": "S1"
        },
```
