### ISSUE TITLE
review usage of minutes used for deployment

### ISSUE THREAD

**Issue by cykreng** [Azure/appservice-landing-zone-accelerator#15]
From Enterprise-Scale-AppService created by [ahmedsza](https://github.com/ahmedsza): cykreng/Enterprise-Scale-AppService#77  

My current run is more than 3.5 hours (still not done). We should review the implications of this in terms of consuming action minutes, and if it blocks other pipelines. I am sure that Azure DevOps task allowed to kickoff a deployment and continue (aka not wait). But cannot find an equivalent for GH Actions.

**Comment by cykreng** [comment]
@ahmedsza  I will check the options however, the default timeout is GitHub Actions:

- **Job execution time** - Each job in a workflow can run for up to **6 hours** of execution time. If a job reaches this limit, the job is terminated and fails to complete.
- **Workflow run time** - Each workflow run is limited to **72 hours**. If a workflow run reaches this limit, the workflow run is cancelled.

You get 20 concurrent job with GitHub free tier

**Comment by kyleburnsdev** [comment]
The Azure Deploy action uses the `az deployment group create` CLI command under the covers and in addition to the "first class" parameters that are fed into the action there is an "additionalArguments" parameter that gets passed along to the underlying command directly. This means that the `--no-wait` parameter of the CLI command should be able to cause the job to immediately return success to the pipeline when the deployment has been successfully queued up for processing by the Azure Resource Manager. What would be lost, however, by doing this would be the ability of the workflow to report success/failure of the deployment and I think that would be a pretty significant cost.

**Comment by kunalbabre** [comment]
Closing old items for now
