### ISSUE TITLE
404 when navigating to config.yaml

### ISSUE THREAD

**Issue by cykreng** [Azure/appservice-landing-zone-accelerator#17]
From Enterprise-Scale-AppService created by [ahmedsza](https://github.com/ahmedsza): cykreng/Enterprise-Scale-AppService#75  

Step 4 on the user guide - Navigate to config.yaml - the link to config.yaml is incorrect

**Comment by cykreng** [comment]
implemented the fix in user guide branch.

**Comment by kunalbabre** [comment]
closing old items for now
