### ISSUE TITLE
Enhancing Multitenant Deployment: Adding Hub Deployment Option and Feature Flag for Optional Resources

### ISSUE THREAD

**Issue by kunalbabre** [Azure/appservice-landing-zone-accelerator#95]
- [x] [Multitenant-all] (Importance: High) I would expect to give users/customers the option to deploy a new Hub and all the required resources or not. I think I have not seen that as a simple feature flag or instruction in the readme docs. 
- [x] [Multitenant-all] (Importance: Medium) some resources are not workload-agnostic. For instance, SQL Database could potentially be substituted by other DBs (i.e. cosmos DB, MongoDB etc.). I believe we should have some kind of "Feature flag" for those resources and let the users/customer decide whether they need them.

**Comment by kunalbabre** [comment]
Bicep implementation is completed for Hub option, TF option pending

**Comment by dmossberg** [comment]
Terraform is completed
